/**
 * CLI-injected bridge between `flue run` and a registered Vite host
 * environment. It selects the requested agent from Flue's canonical scan,
 * then asks the host to mount the normal conversation protocol. Platform
 * setup remains entirely behind the public FlueRunEnvironment contract.
 */
import * as path from 'node:path';
import { normalizePath, type Plugin } from 'vite';
import type { AgentScanResult } from './agent-scan.ts';
import type { FlueResolvedProjectInfo, FlueVitePluginInternalApi } from './flue-plugin.ts';
import { canonicalizePath } from './paths.ts';

export interface RunBridgeOptions {
	/** Absolute path of the module passed to `flue run`. */
	agentModulePath: string;
	/** Agent identity selected by `--name`, when the module exports several. */
	agentName?: string;
	/** Unpredictable URL prefix generated by the CLI for this process. */
	routePrefix: string;
	/** Called once Vite has selected the agent and configured its host. */
	onReady?(info: { identity: string; environment: string; project: FlueResolvedProjectInfo }): void;
}

export function runBridgePlugin(options: RunBridgeOptions): Plugin {
	return {
		name: 'flue-run-bridge',
		apply: 'serve',
		enforce: 'post',
		async configResolved(config) {
			const core = config.plugins.find((plugin) => plugin.name === 'flue');
			const api = core?.api as FlueVitePluginInternalApi | undefined;
			const project = api?.resolved;
			if (!api || !project) {
				throw new Error(
					'[flue] `flue run` could not find a resolved flue() plugin in vite.config.ts.',
				);
			}

			const selected = selectAgent(project.agents, options);
			const configured = await api.configureRunEnvironment({
				agent: selected,
				routePrefix: options.routePrefix,
			});
			options.onReady?.({
				identity: selected.identity,
				environment: configured.name,
				project,
			});
		},
	};
}

function selectAgent(
	agents: readonly AgentScanResult[],
	options: RunBridgeOptions,
): AgentScanResult {
	const requestedPath = normalizePath(canonicalizePath(path.resolve(options.agentModulePath)));
	const candidates = agents.filter(
		(agent) => normalizePath(canonicalizePath(agent.filePath)) === requestedPath,
	);
	const modulePath = options.agentModulePath;
	if (candidates.length === 0) {
		throw new Error(
			`[flue] ${modulePath} is not a registered agent module in this Vite environment. ` +
				"Vite-hosted runs require a top-level 'use agent' directive and the module must match the configured agents scan.",
		);
	}

	const names = candidates.map((candidate) => candidate.identity).join(', ');
	if (options.agentName !== undefined) {
		const matches = candidates.filter((candidate) => candidate.identity === options.agentName);
		const selected = matches[0];
		if (!selected) {
			throw new Error(
				`[flue] --name ${JSON.stringify(options.agentName)} does not match an agent of ${modulePath}. ` +
					`Agents: ${names}.`,
			);
		}
		if (matches.length > 1) {
			throw new Error(
				`[flue] --name ${JSON.stringify(options.agentName)} matches ${matches.length} agents of ${modulePath}. ` +
					'Give each a distinct `agentName`.',
			);
		}
		return selected;
	}

	const selected = candidates[0];
	if (candidates.length > 1 || !selected) {
		throw new Error(
			`[flue] ${modulePath} defines ${candidates.length} agents (${names}). Pick one with --name <agent>.`,
		);
	}
	return selected;
}
